import jsPDF from 'jspdf';
import 'jspdf-autotable';

const COMPANY_NAME = process.env.NEXT_PUBLIC_COMPANY_NAME || 'ServiceFlow';
const COMPANY_EMAIL = process.env.NEXT_PUBLIC_COMPANY_EMAIL || 'info@company.com';
const COMPANY_PHONE = process.env.NEXT_PUBLIC_COMPANY_PHONE || '+94 77 123 4567';
const COMPANY_ADDRESS = process.env.NEXT_PUBLIC_COMPANY_ADDRESS || '123 Business Street';

function addHeader(doc, title) {
  // Company Logo Area
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(COMPANY_NAME, 15, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`${COMPANY_EMAIL} | ${COMPANY_PHONE}`, 15, 27);
  doc.text(COMPANY_ADDRESS, 15, 32);

  // Document Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 195, 20, { align: 'right' });

  doc.setTextColor(0, 0, 0);
  return 42;
}

function addFooter(doc) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Thank you for your business!', 105, pageHeight - 15, { align: 'center' });
  doc.text(`Generated by ${COMPANY_NAME} - ServiceFlow POS System`, 105, pageHeight - 10, { align: 'center' });
}

export function generateQuotationPDF(quotation) {
  const doc = new jsPDF();
  let y = addHeader(doc, 'QUOTATION');

  // Quotation Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Quotation #: ${quotation.quotationNumber}`, 15, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date(quotation.createdAt).toLocaleDateString()}`, 15, y + 6);
  if (quotation.validUntil) {
    doc.text(`Valid Until: ${new Date(quotation.validUntil).toLocaleDateString()}`, 15, y + 12);
  }
  doc.text(`Status: ${quotation.status}`, 15, y + 18);

  // Customer Info
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 120, y);
  doc.setFont('helvetica', 'normal');
  doc.text(quotation.customer?.name || '', 120, y + 6);
  if (quotation.customer?.companyName) doc.text(quotation.customer.companyName, 120, y + 12);
  if (quotation.customer?.email) doc.text(quotation.customer.email, 120, y + 18);
  if (quotation.customer?.phone) doc.text(quotation.customer.phone, 120, y + 24);

  y += 35;

  // Items Table
  const tableData = (quotation.items || []).map((item, i) => [
    i + 1,
    item.serviceName,
    item.description || '',
    item.quantity,
    `LKR ${item.unitPrice?.toLocaleString()}`,
    `${item.discount}%`,
    `${item.tax}%`,
    `LKR ${item.total?.toLocaleString()}`,
  ]);

  doc.autoTable({
    startY: y,
    head: [['#', 'Service', 'Description', 'Qty', 'Unit Price', 'Discount', 'Tax', 'Total']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 35 },
      2: { cellWidth: 40 },
    },
  });

  // Total
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Grand Total: LKR ${quotation.total?.toLocaleString()}`, 195, finalY, { align: 'right' });

  // Notes
  if (quotation.notes) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Notes:', 15, finalY + 10);
    doc.text(quotation.notes, 15, finalY + 16);
  }

  addFooter(doc);
  doc.save(`Quotation_${quotation.quotationNumber}.pdf`);
}

export function generateInvoicePDF(invoice) {
  const doc = new jsPDF();
  let y = addHeader(doc, `${invoice.type} INVOICE`);

  // Invoice Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 15, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 15, y + 6);
  if (invoice.dueDate) {
    doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 15, y + 12);
  }
  doc.text(`Status: ${invoice.status.replace('_', ' ')}`, 15, y + 18);
  doc.text(`Type: ${invoice.type} Invoice`, 15, y + 24);

  // Customer
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 120, y);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.customer?.name || '', 120, y + 6);
  if (invoice.customer?.companyName) doc.text(invoice.customer.companyName, 120, y + 12);
  if (invoice.customer?.email) doc.text(invoice.customer.email, 120, y + 18);
  if (invoice.customer?.phone) doc.text(invoice.customer.phone, 120, y + 24);

  y += 35;

  // Items from quotation
  if (invoice.quotation?.items) {
    const tableData = invoice.quotation.items.map((item, i) => [
      i + 1,
      item.serviceName,
      item.quantity,
      `LKR ${item.unitPrice?.toLocaleString()}`,
      `LKR ${item.total?.toLocaleString()}`,
    ]);

    doc.autoTable({
      startY: y,
      head: [['#', 'Service', 'Qty', 'Unit Price', 'Total']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 9 },
    });

    y = doc.lastAutoTable.finalY + 10;
  }

  // Summary
  doc.setFontSize(10);
  const summaryX = 130;
  doc.text('Invoice Total:', summaryX, y);
  doc.setFont('helvetica', 'bold');
  doc.text(`LKR ${invoice.total?.toLocaleString()}`, 195, y, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.text('Amount Paid:', summaryX, y + 7);
  doc.setTextColor(0, 128, 0);
  doc.text(`LKR ${invoice.amountPaid?.toLocaleString()}`, 195, y + 7, { align: 'right' });

  doc.setTextColor(200, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Balance Due:', summaryX, y + 14);
  doc.text(`LKR ${invoice.balanceDue?.toLocaleString()}`, 195, y + 14, { align: 'right' });

  doc.setTextColor(0, 0, 0);

  // Bank Details
  if (invoice.bankName || invoice.accountNumber) {
    y += 30;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Payment Details:', 15, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    if (invoice.bankName) doc.text(`Bank: ${invoice.bankName}`, 15, y + 7);
    if (invoice.accountName) doc.text(`Account Name: ${invoice.accountName}`, 15, y + 13);
    if (invoice.accountNumber) doc.text(`Account Number: ${invoice.accountNumber}`, 15, y + 19);
    if (invoice.branch) doc.text(`Branch: ${invoice.branch}`, 15, y + 25);
    if (invoice.paymentRef) doc.text(`Reference: ${invoice.paymentRef}`, 15, y + 31);
  }

  addFooter(doc);
  doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
}

export function generateReceiptPDF(payment) {
  const doc = new jsPDF();
  let y = addHeader(doc, 'PAYMENT RECEIPT');

  // Receipt Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Receipt #: ${payment.receipt?.receiptNumber || 'N/A'}`, 15, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date(payment.receivedAt).toLocaleDateString()}`, 15, y + 6);
  doc.text(`Invoice #: ${payment.invoice?.invoiceNumber || 'N/A'}`, 15, y + 12);

  // Customer
  doc.setFont('helvetica', 'bold');
  doc.text('Received From:', 120, y);
  doc.setFont('helvetica', 'normal');
  doc.text(payment.invoice?.customer?.name || '', 120, y + 6);
  if (payment.invoice?.customer?.companyName) {
    doc.text(payment.invoice.customer.companyName, 120, y + 12);
  }

  y += 30;

  // Payment Details
  doc.autoTable({
    startY: y,
    head: [['Description', 'Details']],
    body: [
      ['Amount Received', `LKR ${payment.amount?.toLocaleString()}`],
      ['Payment Method', payment.method?.replace('_', ' ')],
      ['Reference', payment.reference || '-'],
      ['Date Received', new Date(payment.receivedAt).toLocaleDateString()],
      ['Notes', payment.notes || '-'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
  });

  const finalY = doc.lastAutoTable.finalY + 15;

  // Amount in words style
  doc.setFillColor(240, 249, 255);
  doc.rect(15, finalY, 180, 20, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(37, 99, 235);
  doc.text(`Amount Paid: LKR ${payment.amount?.toLocaleString()}`, 105, finalY + 13, { align: 'center' });

  doc.setTextColor(0, 0, 0);

  addFooter(doc);
  doc.save(`Receipt_${payment.receipt?.receiptNumber || 'payment'}.pdf`);
}
